### ISSUE TITLE
Missing Debug files

### ISSUE THREAD

**Issue by SakuraJassen** [Netdex/NEAT.NET#1]
I forked this Project to learn a bit about NEAT and I noticed that the Debug folder is missing. Is there any chance that you still have it?

**Comment by Netdex** [comment]
Hi, thanks for being interested in my project! I've attached the contents of the Debug folder. 
For your information, this is a project I started working on ages ago, and never found the time to complete. I'm not sure I would recommend using it for learning (or anything, for that matter). I would recommend looking at other projects like sharpneat, which are feature complete and well-documented.

[Debug.zip](https://github.com/Netdex/NEAT.NET/files/4433808/Debug.zip)
